// Generated by CoffeeScript 1.4.0
var l;

l = null;

(function() {
  var DistributedLogger;
  DistributedLogger = (function() {

    function DistributedLogger() {}

    DistributedLogger.CELL_LIMIT = 4e5;

    DistributedLogger.EXCEED_PERCENTAGE = 0.8;

    DistributedLogger.prototype.getDb_ = function() {
      return ScriptDb.getMyDb();
    };

    DistributedLogger.prototype.getEmail_ = function() {
      return Session.getActiveUser().getEmail();
    };

    DistributedLogger.prototype.log = function(key, m, sheetName) {
      var body, message, now, sheet, spreadsheet;
      if (sheetName == null) {
        sheetName = null;
      }
      spreadsheet = null;
      now = new Date();
      try {
        if (!key) {
          throw "log: Parameter 'key' is not optional";
        }
        spreadsheet = this.getCurrentSpreadsheet(key);
        if (!spreadsheet) {
          throw "log: spreadsheet wasn't available - did you run 'setup' at least once?";
        }
        if (sheetName) {
          sheet = spreadsheet.getSheetByName(sheetName);
          if (!sheet) {
            sheet = spreadsheet.insertSheet(sheetName);
          }
        } else {
          sheet = spreadsheet.getSheets()[0];
        }
        if (m instanceof Array) {
          message = m.slice(0);
          message.unshift(now);
        } else {
          message = [now, m];
        }
        sheet.appendRow(message);
      } catch (e) {
        Logger.log(e);
        try {
          if (MailApp.getRemainingDailyQuota() > 0) {
            body = "On " + now + ", adding log entries to the spreadsheet: https://docs.google.com/spreadsheet/ccc?key=" + (s.getId()) + " failed because of:\n" + (e.toString()) + "\n-- \nThis email was sent by a user - please do not reply directly!";
            MailApp.sendEmail(spreadsheet.getOwner(), "GAS: DistributedLogger: Error in '" + key + "'", body, {
              noReply: true
            });
          }
        } catch (e) {
          /* we can't do anything about it - if we don't catch this, the user gets an email - we don't want that
          */

          Logger.log(e);
        }
      }
    };

    DistributedLogger.prototype.getCurrentSpreadsheet = function(key) {
      var db, result;
      db = this.getDb_();
      result = db.query({
        key: key
      });
      result = result.sortBy('created', db.DESCENDING);
      if (!result.hasNext()) {
        return null;
      }
      return SpreadsheetApp.openById(result.next().spreadsheet);
    };

    DistributedLogger.prototype.createSpreadsheet = function(key) {
      var now, ob, s;
      now = new Date();
      ob = {
        key: key,
        created: now.getTime()
      };
      s = SpreadsheetApp.create("GAS: DistributedLogger: " + key + " (created " + (now.toUTCString()) + ")");
      s.setAnonymousAccess(false, true);
      ob.spreadsheet = s.getId();
      this.getDb_().save(ob);
      return s;
    };

    DistributedLogger.prototype.isExceeded = function(spreadsheet, percentage) {
      var currentQuota, r, sheet, total, _i, _len, _ref;
      total = 0;
      _ref = spreadsheet.getSheets();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        sheet = _ref[_i];
        r = sheet.getDataRange();
        total += r.getNumRows() * r.getNumColumns();
        currentQuota = total / DistributedLogger.CELL_LIMIT;
        if (currentQuota >= (percentage != null ? percentage : 1)) {
          Logger.log("We used up " + (Number(currentQuota * 100).toPrecision(3)) + "% of all cells");
          return true;
        }
      }
      Logger.log("We only used up " + (Number(currentQuota * 100).toPrecision(3)) + "% of all cells so far");
      return false;
    };

    DistributedLogger.prototype.getQuota = function(key) {
      var r, sheet, spreadsheet, total, _i, _len, _ref;
      if (!key) {
        throw "Parameter 'key' is not optional";
      }
      spreadsheet = this.getCurrentSpreadsheet(key);
      if (!spreadsheet) {
        throw "A spreadsheet for key '" + key + "' does not exist - did you run setup(key)?";
      }
      total = 0;
      _ref = spreadsheet.getSheets();
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        sheet = _ref[_i];
        r = sheet.getDataRange();
        total += r.getNumRows() * r.getNumColumns();
      }
      return total / DistributedLogger.CELL_LIMIT;
    };

    DistributedLogger.prototype.checkQuota = function(key, percentage) {
      var body, create, keys, lock, obj, result, s, v, _i, _len;
      if (key == null) {
        key = null;
      }
      if (percentage == null) {
        percentage = DistributedLogger.EXCEED_PERCENTAGE;
      }
      lock = LockService.getPrivateLock();
      if (lock.tryLock(0)) {
        try {
          if (key) {
            keys = [key];
          } else {
            result = this.getDb_().query({});
            obj = {};
            while (result.hasNext()) {
              obj[result.next().key] = true;
            }
            keys = [];
            for (key in obj) {
              v = obj[key];
              keys.push(key);
            }
          }
          for (_i = 0, _len = keys.length; _i < _len; _i++) {
            key = keys[_i];
            try {
              s = this.getCurrentSpreadsheet(key);
              create = !s || this.isExceeded(s, percentage);
            } catch (e) {
              create = true;
            }
            if (create) {
              s = this.createSpreadsheet(key);
              if (MailApp.getRemainingDailyQuota() > 0) {
                body = "A new spreadsheet for your distributed logging key '" + key + "' has been created.\nYou can find it here: https://docs.google.com/spreadsheet/ccc?key=" + (s.getId());
                MailApp.sendEmail(this.getEmail_(), "GAS: DistributedLogger: '" + key + "' renewed", body, {
                  noReply: true
                });
              }
              return;
            }
          }
        } catch (e) {
          Logger.log(e);
        } finally {
          lock.releaseLock();
        }
      }
    };

    return DistributedLogger;

  })();
  l = new DistributedLogger;
})();


/**
* This keeps the logging spreadsheets alive.
* E.g. creates a new one after hitting X% of the 400,000 cell limit (see here http://support.google.com/drive/bin/answer.py?hl=en&answer=2505921).
*
*
* ***ATTENTION: DO NOT RUN THIS FROM AN END USER ACCOUNT, IT WILL CREATE SPREADSHEETS IN HIS/HER ACCOUNT YOU CAN'T ACCESS***
*
*
* This should be run in a trigger by the receiver of the logs (*not* by the user of the library)
* E.g. if you (lets say adam@host.com) are the developer of the script and want to receive the logs, you should run this in a trigger - whereas one or many of your clients would only use the log method.
*
* How often you will need to run this trigger depends on how much log data is written - rule of thumb is:
* frequencyInMinutes = (users*messagesPerMinute*(messageSize+1)) / 400,000
* Meaning for 10000 users logging ten messages per minute with a size of 3 fields (e.g. an array of length 3) you'd need a trigger running keepAlive every minute.
*
* @param {String} key (Optional) The spreadsheet key to keep alive - if omitted all spreadsheets of the invoking user are kept alive (e.g. renewed)
* @param {number} percentage (Optional, defaults to 0.8) The percentage of the maximum limit (currently 400,000 cells) when to renew a spreadsheet.
*/
function keepAlive(key, percentage) {
  l.checkQuota.apply(l, arguments);
};

/**
* This initializes a new spreadsheet to log to under a given key
*
* ***ATTENTION: DO NOT RUN THIS FROM AN END USER ACCOUNT, IT WILL CREATE SPREADSHEETS IN HIS/HER ACCOUNT YOU CAN'T ACCESS***
*
* @param {String} key The spreadsheet key to prepare for logging.
*/
function setup(key) {
  l.checkQuota(key);
}

/**
* Returns the quota (percentage)
*
* @param {String} key The spreadsheet key to check the quota for.
* @return {number} The percentage between 0.0 and 1.0
*/
function getQuota(key) {
  return l.getQuota(key);
}

/**
* This is the method that does the actual logging.
* Use this from your end user scripts.
* Make sure that each key you use is properly initialized, e.g. setup(key) has been run for it once.
*
* @param {String} key The key of the spreadsheet to log to.
* @param {Object} message The message to log to the spreadsheet. Can be of any type. If it is an array, each field corresponds to one spreadsheet cell. If an array, the maximum size is about 50 (longer arrays have been found to be skipped sometimes). If you are concerned about easily hitting the spreadsheet cell limit, keep the length of the array as small as possible.
* @param {String} sheetName (Optional) a sheet name to log to. Will be inserted as a new spreadsheet if not existent. If omitted, the message will be logged to the first sheet. Be aware that a spreadsheet may not have more than 200 different sheets - see http://support.google.com/drive/bin/answer.py?hl=en&answer=2505921.
*/
function log(key, message, sheetName) {
  l.log.apply(l, arguments);
};

